import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { AuthProvider } from "@/context/AuthContext";
import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import { EmailTemplateProvider } from "@/components/providers/EmailTemplateProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {/* Initialize email templates when app loads */}
            <EmailTemplateProvider />
            <header className="border-b bg-background">
              <div className="container mx-auto flex items-center space-x-4 py-4">
                <Button asChild variant="ghost">
                  <Link href="/">Home</Link>
                </Button>
                <Button asChild variant="ghost">
                  <Link href="/budget">Budget</Link>
                </Button>
                <Button asChild variant="ghost">
                  <Link href="/dashboard">Dashboard</Link>
                </Button>
                <Button asChild variant="ghost">
                  <Link href="/dashboard/gl-codes">GL Codes</Link>
                </Button>
                <Button asChild variant="ghost">
                  <Link href="/dashboard/gl-transactions">GL Transactions</Link>
                </Button>
                <Button asChild variant="ghost">
                  <Link href="/dashboard/journals">Journals</Link>
                </Button>
                <Button asChild variant="ghost">
                  <Link href="/dashboard/accounts">Accounts</Link>
                </Button>
              </div>
            </header>
            {children}
            <Toaster />
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
