import type { Metadata } from "next";
import "./globals.css";
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { AuthProvider } from "@/context/AuthContext";
import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import { EmailTemplateProvider } from "@/components/providers/EmailTemplateProvider";
import MVPNavigation from "@/components/Navigation/MVPNavigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="font-sans antialiased">
        <AuthProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {/* Initialize email templates when app loads */}
            <EmailTemplateProvider />
            <header className="border-b bg-background">
              <div className="container mx-auto flex items-center space-x-4 py-4 overflow-x-auto">
                <MVPNavigation />
              </div>
            </header>
            {children}
            <Toaster />
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
